# Youtube rank exercice

## 1. Importando arquivo e entendendo os dados

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv("topyoutube 3.csv")
df.head(1000)

            Artist Total Views  100M     Avg
0              BTS    27,947.9  63.0   7.370
1        Bad Bunny    27,573.4  66.0  14.555
2    Justin Bieber    27,399.7  37.0   3.986
3       Ed Sheeran    26,894.0  39.0   4.609
4     Taylor Swift    24,350.0  38.0   5.716
..             ...         ...   ...     ...
995   Eric Clapton       789.3   2.0   0.266
996        SanLuis       787.5   2.0   0.192
997     Atitude 67       786.3   1.0   0.146
998     Rusherking       786.1   2.0   1.141
999            SCH       785.3   1.0   0.108

[1000 rows x 4 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1587 entries, 0 to 1586
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Artist       1587 non-null   object
 1   Total Views  1587 non-null   object
 2   100M         1416 non-null   float64
 3   Avg          1587 non-null   float64
dtypes: float64(2), object(2)
memory usage: 49.7+ KB

## 2. Tratar as colunas sem informação adicionando o texto “Não informado”.

In [14]:
df['Total Views'] = df['Total Views'].str.replace(',', '').astype(float)

In [16]:
df['100M'].fillna('não informado', inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1587 entries, 0 to 1586
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Artist       1587 non-null   object
 1   Total Views  1587 non-null   float64
 2   100M         1587 non-null   object
 3   Avg          1587 non-null   float64
dtypes: float64(2), object(2)
memory usage: 49.7+ KB

## 3.Formatar a coluna de total de inscritos multiplicando por 100 milhões

In [21]:
df['Total Views'] = df['Total Views']/100000000

## 4. Formatar coluna “AVG” para 2 casas decimais depois da vírgula.

In [24]:
df['Avg'] = df['Avg'].map(lambda x: '{:.2f}'.format(x))

## 5. Mostrar os top 10 usuários.

In [26]:
top_10_artist = df.sort_values(by='Total Views', ascending=False)

In [28]:
top_10_artist.head(10)

          Artist  Total Views  100M    Avg
0            BTS      27947.9  63.0   7.37
1      Bad Bunny      27573.4  66.0  14.55
2  Justin Bieber      27399.7  37.0   3.99
3     Ed Sheeran      26894.0  39.0   4.61
4   Taylor Swift      24350.0  38.0   5.72
5        Shakira      23961.8  43.0   7.84
6     Katy Perry      23553.4  25.0   3.18
7          Ozuna      22524.8  49.0   4.93
8         Eminem      20937.7  38.0   5.84
9  Ariana Grande      20618.5  37.0   3.37

## 6. Mostrar primeiros 100 usuários por nome decrescente

In [35]:
pd.set_option('display.max_rows', 100) 
top_100_artist = df.sort_values(by='Artist' , ascending=False)

In [36]:
top_100_artist.head(100)

                          Artist  Total Views           100M   Avg
1374                      Łobuzy        396.5            2.0  0.11
537                  İrem Derici       1717.3            3.0  0.32
634                   Ñengo Flow       1388.8            4.0  0.82
1032               Çağatay Akman        742.7            2.0  0.05
350                    will.i.am       2582.0            6.0  0.29
56             twenty one pilots      10147.7           14.0  2.03
1088                    t.A.T.u.        669.8            2.0  0.23
1184                      miss A        574.8            1.0  0.06
401                         iKON       2247.1            3.0  0.32
954                        gnash        834.7            1.0  0.20
1215                        f(x)        544.9            1.0  0.04
955                     deadmau5        834.2  não informado  0.09
464                    blink-182       1962.0            5.0  0.45
1223                 back number        536.6            1.0  0.01
1566                  amazarashi        219.6  não informado  0.05
411                         a-ha       2202.9            1.0  0.75
410                  Zé Vaqueiro       2203.1            7.0  0.99
731                   Zé Ramalho       1204.7            3.0  0.35
57           Zé Neto e Cristiano      10133.5           26.0  1.72
353                    Zé Felipe       2553.0            8.0  2.40
326                          Zoé       2756.3            6.0  0.81
541              Zouhair Bahaoui       1705.7            3.0  0.49
215                Zion & Lennox       3964.3            7.0  1.17
1267                     Zendaya        495.1            1.0  0.05
283                         Zedd       3160.8           10.0  0.46
1194                Zay & Zayion        559.6            1.0  0.03
329                 Zara Larsson       2729.6            4.0  0.30
747                  Zak Chumpae       1174.7            3.0  0.04
1271                        Zaho        492.1            1.0  0.20
447                  Zack Knight       2014.3            3.0  0.54
1177                         ZHU        583.8            2.0  0.18
1166                         ZAZ        596.3  não informado  0.17
184                         ZAYN       4503.5            5.0  0.86
253                      Yuridia       3482.0            7.0  4.55
53    YoungBoy Never Broke Again      10593.7           26.0  4.87
258                   Young Thug       3425.0            8.0  0.93
1278                 Young Money        487.0            1.0  0.07
694                    Young M.A       1267.7            2.0  0.17
1449                      Yohani        326.4            1.0  0.07
60             Yo Yo Honey Singh       9522.4           32.0  3.36
621                     Yo Gotti       1414.7            4.0  0.24
666                        Ylvis       1325.5            1.0  0.14
1341           Yinglee Srijumpol        427.3            1.0  0.04
1108                  Yemi Alade        654.5            1.0  0.13
767                  Yellow Claw       1127.7            3.0  0.17
784                  Yella Beezy       1097.7            2.0  0.21
697                     Yelawolf       1262.1            2.0  0.41
901                Years & Years        917.5            2.0  0.13
1556             Yeah Yeah Yeahs        230.3  não informado  0.08
150             Yasmin Verissimo       5341.8           15.0  2.46
889                Yash Narvekar        938.1            2.0  0.27
245                       Yandel       3544.3            7.0  1.45
462                     YOUNGOHM       1969.0            7.0  0.77
358                    YNW Melly       2534.2            5.0  0.61
396                           YG       2265.6            6.0  0.36
668                    YFN Lucci       1320.2            2.0  0.31
1214                         Y2K        545.2            1.0  0.11
1572                      Xantos        212.7            1.0  0.03
71                  XXXTENTACION       8823.3           18.0  1.61
967                X Ambassadors        820.8            2.0  0.19
1462                 Wyclef Jean        310.9            2.0  0.09
1411                     Woodkid        363.1            1.0  0.08
878                 Wonder Girls        958.4            2.0  0.17
589                      Wolfine       1534.0            2.0  0.27
38                   Wiz Khalifa      12175.3           13.0  1.90
1047           Within Temptation        719.9            1.0  0.20
158               Wisin & Yandel       5158.6           14.0  1.87
142                        Wisin       5578.5           12.0  0.95
627                Willy William       1406.9            2.0  0.32
1558                Willow Smith        230.0            1.0  0.10
917                 Why Don't We        892.3            1.0  0.19
169              Whitney Houston       4918.7           10.0  1.89
1333                  Whitesnake        438.0            2.0  0.09
1536                     Wheatus        246.4            1.0  0.08
571                        Wham!       1580.5            2.0  0.31
361                     Westlife       2515.0            6.0  0.84
85                Wesley Safadão       7529.7           15.0  3.06
802            Weird Al Yankovic       1070.8            2.0  0.23
1002                      Weezer        782.4            1.0  0.18
1430                    Warren G        350.7            1.0  0.10
1228                   Wanna One        531.2            1.0  0.04
811                         Wale       1058.1            3.0  0.22
1453                Wagakki Band        319.8            1.0  0.04
709                       WINNER       1244.0            1.0  0.12
1206               WALK THE MOON        551.5            1.0  0.08
1155                Vũ Duy Khánh        603.6            1.0  0.04
1171              Vázquez Sounds        589.9            1.0  0.04
535              Vremya i Steklo       1721.8            5.0  0.14
675              Vitor Fernandes       1299.4            3.0  0.53
1399                       Vitaa        373.6            1.0  0.07
287               Vishal Dadlani       3122.2            9.0  0.72
257                     Violetta       3428.5            4.0  0.26
1376              Village People        395.6            1.0  0.07
741                 Victor & Leo       1178.9            2.0  0.37
749                    Vicentico       1167.9            3.0  0.41
516                   Via Vallen       1787.5            3.0  0.08
1507                Veysel Mutlu        277.4            1.0  0.03
1358                      Veysel        412.2  não informado  0.06
891                    Vengaboys        934.8            3.0  0.34
864                    Vegedream        991.3            1.0  0.51

## 7. Salvar um novo CSV com a informação tratada.